### ISSUE TITLE
Backend crashes during Discord linking procedure

### ISSUE THREAD

**Issue by Litarvan** [EpiLink/EpiLink#122] opened 2020-04-25 17:47 UTC
Stacktrace : https://code.litarvan.com/zebeh.sql
The Discord ID is the one of the user currently linking his account

It's printed after posting the Discord authcode.

This does not prevent the normal behavior of the bot.

**Comment by utybo** [comment] 2020-04-25 17:47
Duplicate of #121 because talking in voice chat is hard

**Closed** 2020-04-25 17:47 UTC
Labels: Area: Back-end, Status: Duplicate, Type: Bug
